### PR TITLE
:sparkles: add solution server

### LINKED ISSUE #483: Solution Server (MCP Client) Configuration and Authentication
**Goal**: Enable the editor extension to securely communicate with the MCP server in Kubernetes.

Tasks:
- Implement client logic to communicate with solution server over HTTP.
- Handle connection retries and error handling? -- came from ChatGPT but seems reasonable to leave
- Configuration UI for Server Connection. We will need to get the serverURL/port/token and store it safely. Might need another config file 😦 
- Add UI feedback for successful/failed authentication.

### PR DESCRIPTION
**Pull request by djzager**
Fixes #483 

## Summary by CodeRabbit

* **New Features**
  * Added integration with a remote solution server, enabling incident and solution management, success rate retrieval, and hint suggestions.
  * Introduced new user-configurable settings for solution server URL and enablement in the extension.
  * Enhanced incident handling with structured data and improved prompt formatting.
  * Added support for tracking solution and client identifiers across incidents and solutions.
  * Integrated solution server client lifecycle and configuration into the extension with connection management and restart prompts.
  * Added debug logging and refined routing logic based on structured incident data.

* **Bug Fixes**
  * Improved validation and error handling for solution server interactions.

* **Chores**
  * Updated development scripts to support the new agentic workspace.
  * Added new dependencies to support solution server communication and UI enhancements.

### CODE REVIEW

File: agentic/src/clients/solutionServerClient.ts [hunk 1]
```diff
@@ -0,0 +1,417 @@
...
+          if ("text" in chunk) {
+            const content = chunk.text as string;
+            incidentId = parseInt(content, 10);
+            if (isNaN(incidentId)) {
+              throw new Error(`Invalid incident ID returned: ${content}`);
+            }
+            break;
+          }
+        }
+      }
```
[the remark this answers is not in the document]
Comment (djzager) [reply agentic/src/clients/solutionServerClient.ts:276]: Skipping this one.

File: agentic/src/nodes/analysisIssueFix.ts [hunk 2]
```diff
@@ -107,7 +156,9 @@ export class AnalysisIssueFix extends BaseNode {
           return {
             reasoning: `${acc.reasoning}\n${val.outputReasoning}`,
             additionalInfo: `${acc.additionalInfo}\n${val.outputAdditionalInfo}`,
-            uris: acc.uris.concat([relative(this.workspaceDir, val.outputUpdatedFileUri!)]),
+            uris: val.outputUpdatedFileUri
```
Comment (pranavgaikwad) [inline agentic/src/nodes/analysisIssueFix.ts:159]: nice catch

File: agentic/src/workflows/interactiveWorkflow.ts [hunk 3]
```diff
@@ -363,28 +365,55 @@ export class KaiInteractiveWorkflow
   async analysisIssueFixRouterEdge(
     state: typeof AnalysisIssueFixOrchestratorState.State,
   ): Promise<string | string[]> {
+    console.log(`[DEBUG] Edge function called with state:`, {
```
Comment (pranavgaikwad) [inline agentic/src/workflows/interactiveWorkflow.ts:368]: can we make this console.debug()?

File: agentic/src/workflows/interactiveWorkflow.ts [hunk 4]
```diff
@@ -363,28 +365,55 @@ export class KaiInteractiveWorkflow
...
+      (!state.inputFileContent || !state.inputFileUri || state.inputIncidents.length === 0)
     ) {
+      console.log(`[DEBUG] Going back to fix_analysis_issue_router for next incident`);
       return "fix_analysis_issue_router";
     }
+
     // if the router accumulated all responses, we need to go to additional information
     if (state.enableAdditionalInformation) {
       if (state.inputAllAdditionalInfo && state.inputAllReasoning) {
+        console.log(`[DEBUG] Going to summarize both additional info and history`);
```
Comment (pranavgaikwad) [inline agentic/src/workflows/interactiveWorkflow.ts:405]: same with these guys

**Review by pranavgaikwad — APPROVED** [review]
