### PR TITLE
:bug: respect isReadOnly for solution dropdown

### LINKED ISSUE #398: GetSolution button should not be rendered in incident table when in  "read-only" mode
Image

### LINKED ISSUE #400: Issue table styling issues
-  change that button to a link so we can avoid that little indentation at the beginning of the “shoppingCartOrderProcessor.java” field
-  make sure the col widths are set / matching between the header cols and row cols. Shouldnt need to truncate location title if we don’t have to. Also we need some space between the row data. 

Image

### PR DESCRIPTION
**Pull request by djzager**
This PR fixes problems with rendering the incident table(s).
* When isReadOnly, we shouldn't be rendering the solution dropdown
* When isReadOnly, we don't actually need to full rendered path because it gets cluttered
* We need to handle windows paths with care, not just for relative paths but when computing the filename from the incident.uri
* Some other minor tweaks to the look and feel of the table and solution dropdown
 
Fixes #398
Fixes #400

### CODE REVIEW

File: webview-ui/src/components/IncidentTable/IncidentTable.tsx [hunk 1]
```diff
@@ -44,7 +44,13 @@ export const IncidentTable: FC<IncidentTableProps> = ({
     <>
       <Card isPlain>
         <CardHeader
-          actions={{ actions: <GetSolutionDropdown incidents={incidents} scope="in-between" /> }}
+          actions={
```
Comment (ibolton336) [inline webview-ui/src/components/IncidentTable/IncidentTable.tsx:47]: Cleaner option could be:

actions={!isReadOnly && {
  actions: <GetSolutionDropdown incidents={incidents} scope="in-between" />
}}

Comment (djzager) [reply webview-ui/src/components/IncidentTable/IncidentTable.tsx:47]: tried this. It specifically wanted `undefined` or the `{ actions: ... }` so I updated it at the bottom of the table.

File: webview-ui/src/components/IncidentTable/IncidentTable.tsx [hunk 2]
```diff
@@ -54,19 +58,34 @@ export const IncidentTable: FC<IncidentTableProps> = ({
             <Table aria-label="Incidents" variant="compact">
               <Thead>
                 <Tr>
-                  <Th>{ISSUE}</Th>
-                  <Th width={50}>{FOLDER}</Th>
-                  <Th>{LOCATION}</Th>
-                  <Th />
+                  {isReadOnly ? (
+                    <React.Fragment>
```
Comment (sjd78) [inline webview-ui/src/components/IncidentTable/IncidentTable.tsx:62]: `<>` === `<React.Fragment>`

**Review by sjd78 — COMMENTED** [review]
Looks reasonable.

**Comment by djzager** [comment]
After this fix...

The resolution details.
image

Analysis page fix for files at the root of the workspace:
image

Additionally this should fix the paths when grouping by file on windows

**Comment by djzager** [comment]
Updated styling:
image

image

image

**Review by sjd78 — APPROVED** [review]
Changes look good to me.  The link style button looks good.  No buttons in "read only" mode is working great.

**Review by sjd78 — APPROVED** [review]
I'm indifferent to dropping the folder on the resolution view of the incident list.

**Review by ibolton336 — APPROVED** [review]
