### PR TITLE
:bug: load the results even when no rulesets

### LINKED ISSUE #370: Analysis results show incidents even when there are no incidents
Image

After accepting the resolution, the analysis runs and shows that no incidents were found. but, the Analysis View tab still displays incidents.

### PR DESCRIPTION
**Pull request by djzager**
Fixes #370

### CODE REVIEW

**Comment by djzager** [comment]
> Does this still work in a partial analysis?

Don't know yet. Might need to distinguish somehow. But this is to try and see if it fixes specifically what @savitharaghunathan is seeing when we do a full analysis and the results are empty legitimately.

**Review by shawn-hurley — DISMISSED** [review]
VISACK

**Comment by savitharaghunathan** [comment]
tested this without my custom rule and the partial analysis works.

File: vscode/src/client/analyzerClient.ts [hunk 1]
```diff
@@ -539,11 +539,9 @@ export class AnalyzerClient {
           }
           if (ruleSets.length === 0) {
             vscode.window.showInformationMessage("Analysis completed. No incidents were found.");
-            this.fireAnalysisStateChange(false);
-            return;
           }
 
-          vscode.commands.executeCommand("konveyor.loadRuleSets", ruleSets, filePaths);
+          vscode.commands.executeCommand("konveyor.loadRuleSets", ruleSets);
```
Comment (djzager) [inline vscode/src/client/analyzerClient.ts:544]: I did this because the loadRuleSets command only takes 1 argument (ruleSets).

**Comment by djzager** [comment]
I will include the issue to konveyor/java-analyzer-bundle once one exists. We did verify that this fix does not negatively impact partial analysis results AND when the analyzer reports 0 incidents -- we report 0 incidents.

**Review by ibolton336 — APPROVED** [review]
