### PR TITLE
:bug: Move isWaitingForUserInteraction to shared state

### LINKED ISSUE #770: The resolution view gets stuck if the user doesn't finish the previous session
If the user requests a solution but does not press Accept/Reject, or when opening the editor does not press the Continue button before requesting another solution, the previous session remains active. As a result, the new solution will get stuck.

This issue will persist for all subsequent solutions until VS Code is restarted.

**Steps to reproduce:**

- Analyze the coolstore application and request a solution for an incident.

- When the changes and Accept/Reject buttons are displayed, ignore them and immediately request a new solution.

**Expected behavior:**

- Option 1: Requesting a new solution should automatically close the previous session.

- Option 2: The analysis screen should remain locked until the user finishes the previous session.

https://github.com/user-attachments/assets/ad6f7b21-24ee-4c64-b3eb-db5ca0218ab2

### PR DESCRIPTION
**Pull request by ibolton336**
Resolves #770 

## Summary by CodeRabbit

* **New Features**
  * Unified waiting backdrop with contextual messages and an "Open Resolution Panel" button to directly open the resolution panel.
  * Added an explicit action to open the resolution panel.

* **Refactor**
  * Moved the waiting-for-user-interaction flag into persisted extension data and unified how it’s read/updated.
  * Background processing and queue handling now honor the persisted waiting state to avoid work during active user interaction.

### CODE REVIEW

**Review by pranavgaikwad — APPROVED** [review]

**Comment by ibolton336** [comment]
Screenshot 2025-09-04 at 1 27 20 PM

File: webview-ui/src/components/AnalysisPage/AnalysisPage.tsx [hunk 1]
```diff
@@ -344,13 +346,24 @@ const AnalysisPage: React.FC = () => {
...
                   </Title>
+                  {isWaitingForUserInteraction && (
+                    <Button
+                      variant="primary"
+                      onClick={() => dispatch(openResolutionPanel())}
+                      style={{ marginTop: "1rem" }}
+                    >
+                      Open Resolution Panel
+                    </Button>
+                  )}
```
Comment (djzager) [inline webview-ui/src/components/AnalysisPage/AnalysisPage.tsx:366]: I think you should just always show the button.

```suggestion
                    <Button
                      variant="primary"
                      onClick={() => dispatch(openResolutionPanel())}
                      style={{ marginTop: "1rem" }}
                    >
                      Open Resolution Panel
                    </Button>
```

File: webview-ui/src/components/ResolutionsPage/ModifiedFile/ModifiedFileActions.tsx [hunk 2]
```diff
@@ -51,32 +51,52 @@ const DiffStatusBanner: React.FC<{
...
+              ) : (
+                <div>
+                  <strong>All changes have been resolved!</strong>
+                  <br />
+                  <br />
+                  Click <strong>Continue</strong> to resume.
+                  <br />
+                  <br />
+                </div>
+              )
```
Comment (djzager) [inline webview-ui/src/components/ResolutionsPage/ModifiedFile/ModifiedFileActions.tsx:99]: Image

```diff
diff --git a/webview-ui/src/components/ResolutionsPage/ModifiedFile/ModifiedFileActions.tsx b/webview-ui/src/components/ResolutionsPage/ModifiedFile/ModifiedFileActions.tsx
index 642ffd7..363c121 100644
--- a/webview-ui/src/components/ResolutionsPage/ModifiedFile/ModifiedFileActions.tsx
+++ b/webview-ui/src/components/ResolutionsPage/ModifiedFile/ModifiedFileActions.tsx
@@ -92,7 +92,9 @@ const DiffStatusBanner: React.FC<{
                   <strong>All changes have been resolved!</strong>
                   <br />
                   <br />
-                  Click <strong>Continue</strong> to resume.
+                  Click Continue when you have completed any manual modifications to the
+                  solution. When agent mode is enabled, this tells the agent you are ready for
+                  the next step and prevents it from immediately overriding your changes.
                   <br />
                   <br />
                 </div>

```

If you want it to be different words.

**Review by djzager — CHANGES_REQUESTED** [review]
Looks good. A couple comments, only 1 I think you _should_ do.

**Review by pranavgaikwad — DISMISSED** [review]

File: webview-ui/src/components/ResolutionsPage/ModifiedFile/ModifiedFileActions.tsx (hunk 2 above)
Comment (ibolton336) [reply webview-ui/src/components/ResolutionsPage/ModifiedFile/ModifiedFileActions.tsx:99]: @ coderabbitai Can you please open a follow up issue for this ?
