### PR TITLE
:bug: removing the merging logic

### LINKED ISSUE #172: [BUG] After fixing all the incidents in a given violation the violation UI component is still there, but no incidents
Image

After fixing all the incidents in this violation, the violation stays but should be removed.

### PR DESCRIPTION
**Pull request by shawn-hurley**
The analysis engine and backend handles this and returns the entire result

fixes #172 #156 

Built and updated bundle image is based off of commit: [5735da0e228c4b9668b69b938531f42093f713d5](https://github.com/konveyor/java-analyzer-bundle/commit/5735da0e228c4b9668b69b938531f42093f713d5)

### CODE REVIEW

File: vscode/src/data/loadResults.ts [hunk 1]
```diff
@@ -7,81 +7,29 @@ import {
...
-      acc[path] = (acc[path] ?? 0) + (items?.length ?? 0);
-      return acc;
-    },
-    {} as { [key: string]: number },
-  );
 
 export const loadRuleSets = async (
   state: ExtensionState,
   receivedRuleSets: RuleSet[],
   filePaths?: Uri[],
```
Comment (rszwajko) [inline vscode/src/data/loadResults.ts:23]: please remove unused parameter

**Review by rszwajko — CHANGES_REQUESTED** [review]
the PR fixes also partial analysis by providing a new binary - https://github.com/konveyor/editor-extensions/issues/156.
I think we should extract it to another PR with a proper title/message. The description should include the git commit the binary was build.
Removing the merge step looks OK (one minor comment below) but I haven't run the code.

**Comment by rszwajko** [comment]
@shawn-hurley 
I did a smoke test with 2 scenarios  - fixing a single incident and re-introducing the problem (same approach as [in issue 156](https://github.com/konveyor/editor-extensions/issues/156#issuecomment-2542206012)).
Partial analysis seems to work as expected however there is sth wrong with the total number of incidents (`rawIncidentCount`). It keeps growing with every run - starting from 150, then 167 and 186.

Logs:
```
// first run - full analysis
Sending 'analysis_engine.Analyze' request with params: {"label_selector":"(konveyor.io/target=cloud-readiness || konveyor.io/target=discovery || konveyor.io/target=jakarta-ee || konveyor.io/target=quarkus) || (discovery)"}
Response received. Summary: {"wellFormed":true,"rawIncidentCount":150,"incidentCount":150,"partialAnalysis":{}}

// 2nd run - fixed one incident (manually)
Sending 'analysis_engine.Analyze' request with params: {"label_selector":"(konveyor.io/target=cloud-readiness || konveyor.io/target=discovery || konveyor.io/target=jakarta-ee || konveyor.io/target=quarkus) || (discovery)","included_paths":["/home/rszwajko/repos/coolstore/src/main/java/com/redhat/coolstore/model/InventoryEntity.java"]}
Response received. Summary: {"wellFormed":true,"rawIncidentCount":167,"incidentCount":167,"partialAnalysis":{"incidentsBefore":6,"incidentsAfter":5}}

// 3rd run - re-introduced the same incident
Sending 'analysis_engine.Analyze' request with params: {"label_selector":"(konveyor.io/target=cloud-readiness || konveyor.io/target=discovery || konveyor.io/target=jakarta-ee || konveyor.io/target=quarkus) || (discovery)","included_paths":["/home/rszwajko/repos/coolstore/src/main/java/com/redhat/coolstore/model/InventoryEntity.java"]}
Response received. Summary: {"wellFormed":true,"rawIncidentCount":186,"incidentCount":186,"partialAnalysis":{"incidentsBefore":5,"incidentsAfter":6}}
```

**Comment by shawn-hurley** [comment]
This is related to the ignore directory problem because we store the code snips in the reports and save those to disk. The analyzer is finding the new issues, just in the newly created file. 

I don't think there is a front-end fix for this; I think the front-end displaying what the analyzer gives it makes some sense. 

Thoughts?

File: vscode/src/data/loadResults.ts (hunk 1 above)
Comment (shawn-hurley) [reply vscode/src/data/loadResults.ts]: updated

**Review by rszwajko — APPROVED** [review]
